global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "mean-app"
    static_configs:
      - targets: ["mean-app:3000"]
    metrics_path: "/metrics"
    scrape_interval: 10s
