global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "mean_app_uptime"
    metrics_path: /api/test
    static_configs:
      - targets: ["recept-gyujtemeny.onrender.com:443"]
    scheme: https
